#-----------------------MyCoin-------------------
mycoin:
    build: . 
    env_file:
        - mycoin.env 
    command: gunicorn --name mycoin -b 0.0.0.0:5488 -w 2 wsgi:app 
    ports: 
        - "5488:5488"
    volumes:
        - .:/mycoin 
   # external_links:
    #    - mysql-coin:ut8-mysql
    links:
        - redis1

#-------------------- celery --------------------------
celery:
    build: .
    env_file:
        - mycoin.env
    command: celery worker -A mycoin.mails.celery_app --loglevel=INFO
    volumes:
        - .:/mycoin
    links:
        - redis1


#------------------- redis servers---------------------
redis1:
    image: redis
    command: redis-server --port 6385
    ports:
        - "6385:6385"

